### ISSUE TITLE
User Authentication and Verification

### ISSUE THREAD

**Issue by moswil** [moswil/blog_app#3]
- [ ] Create a database model for user registration
- [ ] Create the required forms and templates
- [ ] Add the logic for user registration
- [ ] Write tests the user registration logic
- [ ] Add the logic for user authentication/login
- [ ] Write tests for user authentication
- [ ] Create the database model for user verification
- [ ] Add the logic for user verification via sending an email to verify the account
- [ ] Write tests for user verification
- [ ] Create database models for Password Reset
- [ ] Add the logic for password resetting
- [ ] Write tests for password resetting
